name: footprint-tools
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.6
- pip
- tqdm
- cython
- numpy
- scipy
- pandas
- statsmodels
- simplejson
- pysam
- tqdm
- argh
- matplotlib
- colorlog

- pip:
  - pwlf
  - genome_tools
  - .
