name: footprint-tools
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.6
- pip
- tqdm
- cython
- numpy
- scipy
- pandas
- statsmodels
- simplejson
- tqdm
- click
- matplotlib

- pip:
  - git+https://github.com/jvierstra/pysam.git
  - pwlf
  - genome_tools
  - yapsin
  - .
