name: footprint-tools
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.6
- pip
- tqdm
- cython
- numpy>=1.10
- scipy>=0.17
- pandas
- statsmodels
- simplejson
- pysam
- tqdm

- pip:
  - pwlf
  - genome_tools
  - .
